import Head from "next/head";
import AboutUs from "~/components/about-us";
import Footer from "~/components/footer";
import OurPastors from "~/components/our-pastors";
import Welcome from "~/components/welcome";
import WhatWeDo from "~/components/what-we-do";
import WhereAreWe from "~/components/where-are-we";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>PerkiWeb</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Welcome />
      <AboutUs />
      <WhatWeDo />
      <OurPastors />
      <WhereAreWe />
      <Footer />
    </>
  );
}
